### PR TITLE
Add an option to generate links to login an user.

### PR DESCRIPTION
**Pull request by mworrell**

### CODE REVIEW

**Comment by mworrell** [comment]
@mmzeeman could you have a look at this?

Also needs a merge to the 1.x version of this module.

**Comment by mmzeeman** [comment]
Looks fine to me. Only, shouldn't the model also check if the user account is enabled (published)?

**Comment by mworrell** [comment]
Good one.  Will add that check.

I think this was being added for the "log in via email" feature.

**Comment by mworrell** [comment]
Am wondering how this should work with 2FA.

And if the model should have a `use` check on `mod_access_url` (especially in the master, which exposes all models).

**Pull request merged**
